const axios = require('axios');

class DelhiveryService {
    constructor() {
        this.apiKey = process.env.DELHIVERY_API_KEY;
        this.baseUrl = process.env.DELHIVERY_BASE_URL || 'https://track.delhivery.com/api';
        this.surfaceApiUrl = process.env.DELHIVERY_SURFACE_API_URL || 'https://track.delhivery.com/api/cmu/create.json';
        this.trackingUrl = process.env.DELHIVERY_TRACKING_URL || 'https://track.delhivery.com/api/v1/packages/json';
    }

    // Get delivery rates
    async getDeliveryRates(params) {
        try {
            const { fromPincode, toPincode, weight, codAmount = 0 } = params;

            const requestData = {
                md: 'S', // Mode: Surface
                ss: 'Delivered', // Status
                d_pin: toPincode,
                o_pin: fromPincode,
                cgm: weight * 1000, // Convert kg to grams
                pt: codAmount > 0 ? 'COD' : 'Pre-paid'
            };

            const response = await axios.get(`${this.baseUrl}/kinko/v1/invoice/charges/.json`, {
                params: requestData,
                headers: {
                    'Authorization': `Token ${this.apiKey}`,
                    'Content-Type': 'application/json'
                }
            });

            if (response.data && response.data[0]) {
                const rateData = response.data[0];
                return {
                    success: true,
                    data: {
                        totalAmount: rateData.total_amount || 0,
                        baseRate: rateData.freight_amount || 0,
                        codCharges: rateData.cod_amount || 0,
                        fuelSurcharge: rateData.fuel_surcharge || 0,
                        serviceTax: rateData.service_tax || 0,
                        estimatedDays: '2-4',
                        currency: 'INR'
                    }
                };
            }

            return {
                success: false,
                error: 'No rate data available'
            };

        } catch (error) {
            console.error('Delhivery rate calculation error:', error.response?.data || error.message);
            return {
                success: false,
                error: error.response?.data?.message || error.message
            };
        }
    }

    // Create shipment
    async createShipment(orderData) {
        try {
            const {
                orderId,
                orderNumber,
                customerName,
                customerPhone,
                customerEmail,
                shippingAddress,
                items,
                codAmount = 0,
                weight = 1
            } = orderData;

            const shipmentData = {
                shipments: [{
                    name: customerName,
                    add: `${shippingAddress.addressLine1}, ${shippingAddress.addressLine2 || ''}`.trim(),
                    pin: shippingAddress.postalCode,
                    city: shippingAddress.city,
                    state: shippingAddress.state,
                    country: shippingAddress.country || 'India',
                    phone: customerPhone,
                    order: orderNumber,
                    payment_mode: codAmount > 0 ? 'COD' : 'Prepaid',
                    return_pin: process.env.RETURN_PINCODE || '110001',
                    return_city: process.env.RETURN_CITY || 'New Delhi',
                    return_phone: process.env.RETURN_PHONE || '9999999999',
                    return_add: process.env.RETURN_ADDRESS || 'Return Address',
                    return_state: process.env.RETURN_STATE || 'Delhi',
                    return_country: 'India',
                    products_desc: items.map(item => item.name).join(', '),
                    hsn_code: '9999',
                    cod_amount: codAmount,
                    order_date: new Date().toISOString().split('T')[0],
                    total_amount: codAmount,
                    seller_add: process.env.SELLER_ADDRESS || 'Seller Address',
                    seller_name: process.env.SELLER_NAME || 'Ghanshyam Murti Bhandar',
                    seller_inv: orderNumber,
                    quantity: items.reduce((sum, item) => sum + item.quantity, 0),
                    waybill: '', // Will be generated by Delhivery
                    shipment_width: 10,
                    shipment_height: 10,
                    weight: weight,
                    seller_gst_tin: process.env.SELLER_GST || '',
                    shipping_mode: 'Surface',
                    address_type: 'home'
                }]
            };

            const response = await axios.post(this.surfaceApiUrl, 
                `format=json&data=${JSON.stringify(shipmentData)}`,
                {
                    headers: {
                        'Authorization': `Token ${this.apiKey}`,
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }
            );

            if (response.data && response.data.packages) {
                const packageData = response.data.packages[0];
                return {
                    success: true,
                    data: {
                        waybill: packageData.waybill,
                        refnum: packageData.refnum,
                        status: packageData.status,
                        remarks: packageData.remarks,
                        trackingUrl: `https://www.delhivery.com/track/package/${packageData.waybill}`
                    }
                };
            }

            return {
                success: false,
                error: response.data?.rmk || 'Failed to create shipment'
            };

        } catch (error) {
            console.error('Delhivery shipment creation error:', error.response?.data || error.message);
            return {
                success: false,
                error: error.response?.data?.rmk || error.message
            };
        }
    }

    // Track shipment
    async trackShipment(waybill) {
        try {
            const response = await axios.get(this.trackingUrl, {
                params: {
                    waybill: waybill,
                    verbose: 3
                },
                headers: {
                    'Authorization': `Token ${this.apiKey}`,
                    'Content-Type': 'application/json'
                }
            });

            if (response.data && response.data.ShipmentData) {
                const shipmentData = response.data.ShipmentData[0];
                const shipment = shipmentData.Shipment;
                
                return {
                    success: true,
                    data: {
                        waybill: shipment.AWB,
                        status: shipment.Status.Status,
                        statusDate: shipment.Status.StatusDateTime,
                        origin: shipment.Origin,
                        destination: shipment.Destination,
                        estimatedDelivery: shipment.ExpectedDeliveryDate,
                        currentLocation: shipment.Status.Instructions,
                        scans: shipment.Scans || []
                    }
                };
            }

            return {
                success: false,
                error: 'No tracking data available'
            };

        } catch (error) {
            console.error('Delhivery tracking error:', error.response?.data || error.message);
            return {
                success: false,
                error: error.response?.data?.message || error.message
            };
        }
    }

    // Check serviceability
    async checkServiceability(pincode) {
        try {
            const response = await axios.get(`${this.baseUrl}/c/api/pin-codes/json/`, {
                params: {
                    token: this.apiKey,
                    filter_codes: pincode
                }
            });

            if (response.data && response.data.delivery_codes) {
                const serviceData = response.data.delivery_codes[0];
                return {
                    success: true,
                    data: {
                        pincode: serviceData.postal_code.pin,
                        city: serviceData.postal_code.city,
                        state: serviceData.postal_code.state_code,
                        isServiceable: serviceData.cod === 'Y' || serviceData.pre_paid === 'Y',
                        codAvailable: serviceData.cod === 'Y',
                        prepaidAvailable: serviceData.pre_paid === 'Y',
                        cashPickupAvailable: serviceData.pickup === 'Y',
                        repl: serviceData.repl === 'Y',
                        is_oda: serviceData.is_oda === 'Y'
                    }
                };
            }

            return {
                success: false,
                error: 'Pincode not serviceable'
            };

        } catch (error) {
            console.error('Delhivery serviceability check error:', error.response?.data || error.message);
            return {
                success: false,
                error: error.response?.data?.message || error.message
            };
        }
    }

    // Cancel shipment
    async cancelShipment(waybill) {
        try {
            const response = await axios.post(`${this.baseUrl}/api/p/edit`, {
                waybill: waybill,
                cancellation: true
            }, {
                headers: {
                    'Authorization': `Token ${this.apiKey}`,
                    'Content-Type': 'application/json'
                }
            });

            return {
                success: true,
                data: response.data
            };

        } catch (error) {
            console.error('Delhivery cancellation error:', error.response?.data || error.message);
            return {
                success: false,
                error: error.response?.data?.message || error.message
            };
        }
    }
}

module.exports = new DelhiveryService();
